apiVersion: v1
kind: ServiceAccount
metadata:
  name: ach-to-rtp-service
  namespace: default
  labels:
    app: ach-to-rtp-service

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ach-to-rtp-service
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ach-to-rtp-service
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ach-to-rtp-service
subjects:
- kind: ServiceAccount
  name: ach-to-rtp-service
  namespace: default
