apiVersion: v1
kind: Secret
metadata:
  name: ach-rtp-secrets
  namespace: default
type: Opaque
stringData:
  db-username: postgres
  db-password: "CHANGE_ME_IN_PRODUCTION"
  rabbitmq-username: guest
  rabbitmq-password: "CHANGE_ME_IN_PRODUCTION"
